### ISSUE TITLE
準備委員会個人有志としての記載

### ISSUE THREAD

**Issue by syunsuke** [rea-osaka/rea-osaka.github.io#5]
aboutのぺーじに、有志として参加する人の名前を記載しています

とりあえずは私、福田と大江先生にしてありますが、
まずは、委員会内で他に参加される先生がおられれば、記載しますので連絡ください

**Comment by Shigenobu-Nagao** [comment]
勇気を出して、長尾、参加します！！

**Comment by syunsuke** [comment]
承知しました。長尾先生の名前をaboutのページに追加します。

**Comment by syunsuke** [comment]
小委員会になったのでクローズします
